#include "LinearRegressionModel.h"

// Instantiate the model generated by micromlgen
Eloquent::ML::Port::LinearRegression linReg;

void setup() {
    Serial.begin(115200);
    while (!Serial);
}

void loop() {
    if (Serial.available() > 0) {
        // Read incoming X test value from Python
        float x_val = Serial.parseFloat();

        // Clear any leftover newline bytes
        while (Serial.available() > 0) {
            Serial.read();
        }

        // Run inference on the ATmega328P processor
        float input[1] = {x_val};
        float y_pred = linReg.predict(input);

        // Send the hardware prediction back to Python
        Serial.println(y_pred, 6);
    }
}